name: librenms

services:
  db:
    image: mariadb:10.5
    container_name: librenms_db
    command:
      - "mysqld"
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ=${TZ}"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    restart: always

  redis:
    image: redis:5.0-alpine
    container_name: librenms_redis
    environment:
      - "TZ=${TZ}"
    restart: always

  # msmtpd:
  #   image: crazymax/msmtpd:latest
  #   container_name: librenms_msmtpd
  #   environment:
  #     - "SMTP_HOST=${SMTP_HOST}"
  #     - "SMTP_PORT=${SMTP_PORT}"
  #     - "SMTP_TLS=${SMTP_TLS}"
  #     - "SMTP_STARTTLS=${SMTP_STARTTLS}"
  #     - "SMTP_TLS_CHECKCERT=${SMTP_TLS_CHECKCERT}"
  #     - "SMTP_AUTH=${SMTP_AUTH}"
  #     - "SMTP_USER=${SMTP_USER}"
  #     - "SMTP_PASSWORD=${SMTP_PASSWORD}"
  #     - "SMTP_FROM=${SMTP_FROM}"
  #   restart: always

  librenms:
    image: librenms/librenms:latest
    container_name: librenms
    hostname: librenms
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - target: 8000
        published: 8111
        protocol: tcp
    depends_on:
      - db
      - redis
      # - msmtpd
    volumes:
      - "./librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "MEMORY_LIMIT=${MEMORY_LIMIT}"
      - "MAX_INPUT_VARS=${MAX_INPUT_VARS}"
      - "UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE}"
      - "OPCACHE_MEM_SIZE=${OPCACHE_MEM_SIZE}"
      - "REAL_IP_FROM=${REAL_IP_FROM}"
      - "REAL_IP_HEADER=${REAL_IP_HEADER}"
      - "LOG_IP_VAR=${LOG_IP_VAR}"
      - "CACHE_DRIVER=${CACHE_DRIVER}"
      - "SESSION_DRIVER=${SESSION_DRIVER}"
      - "REDIS_HOST=${REDIS_HOST}"
      - "LIBRENMS_SNMP_COMMUNITY=${LIBRENMS_SNMP_COMMUNITY}"
      - "LIBRENMS_WEATHERMAP=${LIBRENMS_WEATHERMAP}"
      - "LIBRENMS_WEATHERMAP_SCHEDULE=${LIBRENMS_WEATHERMAP_SCHEDULE}"
    restart: always

  dispatcher:
    image: librenms/librenms:latest
    container_name: librenms_dispatcher
    hostname: librenms-dispatcher
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    volumes:
      - "./librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "DISPATCHER_NODE_ID=dispatcher1"
      - "SIDECAR_DISPATCHER=1"
      - "MEMORY_LIMIT=${MEMORY_LIMIT}"
      - "MAX_INPUT_VARS=${MAX_INPUT_VARS}"
      - "UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE}"
      - "OPCACHE_MEM_SIZE=${OPCACHE_MEM_SIZE}"
      - "REAL_IP_FROM=${REAL_IP_FROM}"
      - "REAL_IP_HEADER=${REAL_IP_HEADER}"
      - "LOG_IP_VAR=${LOG_IP_VAR}"
      - "CACHE_DRIVER=${CACHE_DRIVER}"
      - "SESSION_DRIVER=${SESSION_DRIVER}"
      - "REDIS_HOST=${REDIS_HOST}"
      - "LIBRENMS_SNMP_COMMUNITY=${LIBRENMS_SNMP_COMMUNITY}"
      - "LIBRENMS_WEATHERMAP=${LIBRENMS_WEATHERMAP}"
      - "LIBRENMS_WEATHERMAP_SCHEDULE=${LIBRENMS_WEATHERMAP_SCHEDULE}"
    restart: always

  syslogng:
    image: librenms/librenms:latest
    container_name: librenms_syslogng
    hostname: librenms-syslogng
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    ports:
      - target: 514
        published: 514
        protocol: tcp
      - target: 514
        published: 514
        protocol: udp
    volumes:
      - "./librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "SIDECAR_SYSLOGNG=1"
      - "MEMORY_LIMIT=${MEMORY_LIMIT}"
      - "MAX_INPUT_VARS=${MAX_INPUT_VARS}"
      - "UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE}"
      - "OPCACHE_MEM_SIZE=${OPCACHE_MEM_SIZE}"
      - "REAL_IP_FROM=${REAL_IP_FROM}"
      - "REAL_IP_HEADER=${REAL_IP_HEADER}"
      - "LOG_IP_VAR=${LOG_IP_VAR}"
      - "CACHE_DRIVER=${CACHE_DRIVER}"
      - "SESSION_DRIVER=${SESSION_DRIVER}"
      - "REDIS_HOST=${REDIS_HOST}"
      - "LIBRENMS_SNMP_COMMUNITY=${LIBRENMS_SNMP_COMMUNITY}"
      - "LIBRENMS_WEATHERMAP=${LIBRENMS_WEATHERMAP}"
      - "LIBRENMS_WEATHERMAP_SCHEDULE=${LIBRENMS_WEATHERMAP_SCHEDULE}"
    restart: always

  snmptrapd:
    image: librenms/librenms:latest
    container_name: librenms_snmptrapd
    hostname: librenms-snmptrapd
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    ports:
      - target: 162
        published: 162
        protocol: tcp
      - target: 162
        published: 162
        protocol: udp
    volumes:
      - "./librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "SIDECAR_SNMPTRAPD=1"
      - "MEMORY_LIMIT=${MEMORY_LIMIT}"
      - "MAX_INPUT_VARS=${MAX_INPUT_VARS}"
      - "UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE}"
      - "OPCACHE_MEM_SIZE=${OPCACHE_MEM_SIZE}"
      - "REAL_IP_FROM=${REAL_IP_FROM}"
      - "REAL_IP_HEADER=${REAL_IP_HEADER}"
      - "LOG_IP_VAR=${LOG_IP_VAR}"
      - "CACHE_DRIVER=${CACHE_DRIVER}"
      - "SESSION_DRIVER=${SESSION_DRIVER}"
      - "REDIS_HOST=${REDIS_HOST}"
      - "LIBRENMS_SNMP_COMMUNITY=${LIBRENMS_SNMP_COMMUNITY}"
      - "LIBRENMS_WEATHERMAP=${LIBRENMS_WEATHERMAP}"
      - "LIBRENMS_WEATHERMAP_SCHEDULE=${LIBRENMS_WEATHERMAP_SCHEDULE}"
    restart: always
